/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b4c5ff",
        "on-secondary-fixed": "#002113",
        "primary": "#004ac6",
        "surface-tint": "#0053db",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "tertiary-container": "#996100",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        "secondary": "#006c49",
        "on-secondary-container": "#00714d",
        "surface-container-high": "#e2e8f8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-background": "#151c27",
        "on-secondary": "#ffffff",
        "primary-container": "#2563eb",
        "on-tertiary-container": "#ffeedd",
        "surface-variant": "#dce2f3",
        "surface-container": "#e7eefe",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-bright": "#f9f9ff",
        "outline": "#737686",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dce2f3",
        "inverse-on-surface": "#ebf1ff",
        "on-primary-container": "#eeefff",
        "tertiary": "#784b00",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-low": "#f0f3ff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#151c27",
        "surface-dim": "#d3daea",
        "error-container": "#ffdad6",
        "background": "#f9f9ff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "surface": "#f9f9ff",
        "inverse-surface": "#2a313d",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c3c6d7",
        "secondary-container": "#6cf8bb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "24px",
        "sidebar-width": "260px",
        "container-max": "1440px",
        "base": "4px",
        "lg": "32px",
        "xl": "48px",
        "sm": "16px",
        "xs": "8px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
